### ISSUE TITLE
~60 datasets from 2010 - mid-2021?

### ISSUE THREAD

**Issue by marklit** [opengeos/maxar-open-data#10]
There appears to be ~60 datasets listed on https://www.maxar.com/open-data which aren't linked to in this repo. Are there any plans to add them?

**Comment by giswqs** [comment]
The data come from the this STAC catalog. I can only add data from this catalog.

https://radiantearth.github.io/stac-browser/#/external/maxar-opendata.s3.amazonaws.com/events/catalog.json

**Comment by giswqs** [comment]
Those datasets on the Maxar website require registration. I can't redistribute them without permission. The datasets from the STAC catalog are freely accessible.

**Comment by marklit** [comment]
Okay, that makes sense.
