### ISSUE TITLE
ValueError: '10300500E4F91900' is not in list

### ISSUE THREAD

**Issue by Tuxedomask95** [opengeos/maxar-open-data#12]
When we change the dataset, it can not find previously selected COG mosaic and throws below error:

ValueError: '10300500E4F91900' is not in list
Traceback:
File "/home/user/.local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/home/user/app/app.py", line 41, in <module>
    catalog = st.selectbox('Select a COG mosaic', get_catalogs(dataset), index=get_catalogs(dataset).index('10300500E4F91900'))

**Comment by giswqs** [comment]
I don't maintain the streamlit web app any more. Try out the new version using Solara: https://huggingface.co/spaces/giswqs/solara-maxar
