### ISSUE TITLE
KeyError: 'tiles'

### ISSUE THREAD

**Issue by oscarbau** [opengeos/maxar-open-data#13]
Hi, I am trying to reproduce the example to load and visualize Maxar images:
 
 Leafmap version:
 0.21.3
 
m = leafmap.Map()
url = 'https://open.gishub.org/maxar-open-data/datasets/Kahramanmaras-turkey-earthquake-23/1050050044DE7E00.json'
m.add_stac_layer(url, name="Mosaic")
m

But I am getting this error:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[11], line 3
      1 m = leafmap.Map()
      2 url = 'https://open.gishub.org/maxar-open-data/datasets/Kahramanmaras-turkey-earthquake-23/1050050044DE7E00.json'
----> 3 m.add_stac_layer(url, name="Mosaic")
      4 m

File ~\miniconda3\envs\geo\lib\site-packages\leafmap\leafmap.py:924, in Map.add_stac_layer(self, url, collection, item, assets, bands, titiler_endpoint, name, attribution, opacity, shown, fit_bounds, **kwargs)
    894 def add_stac_layer(
    895     self,
    896     url=None,
   (...)
    907     **kwargs,
    908 ):
    909     """Adds a STAC TileLayer to the map.
    910 
    911     Args:
   (...)
    922         fit_bounds (bool, optional): A flag indicating whether the map should be zoomed to the layer extent. Defaults to True.
    923     """
--> 924     tile_url = stac_tile(
    925         url, collection, item, assets, bands, titiler_endpoint, **kwargs
    926     )
    927     bounds = stac_bounds(url, collection, item, titiler_endpoint)
    928     self.add_tile_layer(tile_url, name, attribution, opacity, shown)

File ~\miniconda3\envs\geo\lib\site-packages\leafmap\stac.py:674, in stac_tile(url, collection, item, assets, bands, titiler_endpoint, **kwargs)
    671     else:
    672         r = requests.get(titiler_endpoint.url_for_stac_item(), params=kwargs).json()
--> 674 return r["tiles"][0]

KeyError: 'tiles'

Thanks in advance for looking into it.

**Comment by giswqs** [comment]
Please update leafmap to the latest version.
