### ISSUE TITLE
Incorrect URL in streamlit_app.py

### ISSUE THREAD

**Issue by desilvarami** [opengeos/maxar-open-data#2]
Dear Professor, thank you very much for all your contributions to the open geospatial world. 

I have noticed that this streamlit_app.py is no longer working (https://maxar-open-data.streamlit.app/). Probably because the URL  "https://giswqs.github.io/maxar-open-data" no longer exists. I've noticed that the repo (https://github.com/giswqs/maxar-open-data/blob/master/datasets ) also redirects to "https://github.com/opengeos/maxar-open-data/tree/master/datasets". Kindly look into this mater, as this application was found to be very useful to find pre and post disaster images during an emergency. 
Thank you.

**Comment by giswqs** [comment]
It has been fixed. https://maxar-open-data.streamlit.app/

**Comment by desilvarami** [comment]
Thank you very much Professor.
