### ISSUE TITLE
Visualizing the Morrocco "after" datasets

### ISSUE THREAD

**Issue by GGDRriedel** [opengeos/maxar-open-data#3]
Hi there and thanks for the work!

I am trying to visualize the Morrocco dataset and followed the examples on how to get the collection of the "after"  pictures. 
However I can't figure out how to use the collection to actually visualize the iamges themseves. 

Any hint would be much apreciated.

**Comment by giswqs** [comment]
Demo: https://youtu.be/RBjZ5Ju09iU
Tutorial: https://youtu.be/8t5M-EGR0sA
