### ISSUE TITLE
How to get longitude/Latitudes as well as images for these events?

### ISSUE THREAD

**Issue by ShreelekhaR** [opengeos/maxar-open-data#4]
Hi, very excited about this repo. How can we retrieve the lon/lat for a tile?

**Comment by giswqs** [comment]
See https://leafmap.org/notebooks/03_cog_stac/

**Comment by ShreelekhaR** [comment]
Awesome! Thank you.

**Comment by ShreelekhaR** [comment]
So if we wanted to retrieve the latlon of the maxar tiles, we would need to parse the json?

**Comment by giswqs** [comment]
You can read the corresponding GeoJSON file to get lat/lon for whatever tile you are interested in.
https://github.com/opengeos/maxar-open-data/blob/master/datasets/BayofBengal-Cyclone-Mocha-May-23.geojson
